import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Main intro sidebar
  introSidebar: [
    'intro',
  ],
  
  // DSA Knowledge sidebar
  dsaSidebar: [
    {
      type: 'autogenerated',
      dirName: 'dsa-knowledge',
    },
  ],
  
  // JavaScript Knowledge sidebar
  javascriptSidebar: [
    {
      type: 'autogenerated',
      dirName: 'javascript-knowledge',
    },
  ],
  
  // React Knowledge sidebar
  reactSidebar: [
    {
      type: 'autogenerated',
      dirName: 'react-knowledge',
    },
  ],
};

export default sidebars;
