import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Main knowledge sidebar with organized sections
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'DSA Knowledge',
      items: [
        {
          type: 'autogenerated',
          dirName: 'dsa-knowledge',
        },
      ],
    },
    {
      type: 'category',
      label: 'JavaScript Knowledge',
      items: [
        {
          type: 'autogenerated',
          dirName: 'javascript-knowledge',
        },
      ],
    },
    {
      type: 'category',
      label: 'React Knowledge',
      items: [
        {
          type: 'autogenerated',
          dirName: 'react-knowledge',
        },
      ],
    },
  ],
};

export default sidebars;
